
const CallList = [
  {
    id: 0,
    img: 'imageLink',
    name: 'rahul',
    online: true,
    incoming: true,
    missed: false,
  },
  {
    id: 1,
    img: 'imageLink',
    name: 'vvfsdfv',
    online: true,
    incoming: false,
    missed: true,
  },
  {
    id: 2,
    img: 'imageLink',
    name: 'sfafdfds',
    online: false,
    incoming: true,
    missed: true,
  },
  {
    id: 3,
    img: 'imageLink',
    name: 'dfsffds',
    online: false,
    incoming: false,
    missed: false,
  },
  {
    id: 4,
    img: 'imageLink',
    name: 'aman',
    online: true,
    incoming: true,
    missed: false,
  },
  {
    id: 5,
    img: 'imageLink',
    name: 'vimal',
    online: false,
    incoming: false,
    missed: false,
  },
  {
    id: 6,
    img: 'imageLink',
    name: 'ankita',
    online: true,
    incoming: true,
    missed: false,
  },
  {
    id: 7,
    img: 'imageLink',
    name: 'bhvgv',
    online: false,
    incoming: false,
    missed: false,
  },
  {
    id: 8,
    img: 'imageLink',
    name: 'dsfsg',
    online: true,
    incoming: true,
    missed: false,
  },
  {
    id: 9,
    img: 'imageLink',
    name: 'dfsarf',
    online: false,
    incoming: false,
    missed: false,
  },
  {
    id: 10,
    img: 'imageLink',
    name: 'fsag',
    online: true,
    incoming: true,
    missed: false,
  },
  {
    id: 11,
    img: 'imageLink',
    name: 'grtfgt',
    online: false,
    incoming: false,
    missed: false,
  },
  {
    id: 12,
    img: 'imageLink',
    name: 'rggre',
    online: true,
    incoming: true,
    missed: false,
  },
];

const ChatList = [
  {
    id: 0,
    img: 'imageLink',
    name: 'rttrg',
    msg: 'songName',
    time: "9:36",
    unread: 0,
    pinned: true,
    online: true,
  },
  {
    id: 1,
    img: 'imageLink',
    name: 'rtte',
    msg: 'vdssssssfsgaaaaaaaaaaaaaaaa',
    time: "12:02",
    unread: 2,
    pinned: true,
    online: false,
  },
  {
    id: 2,
    img: 'imageLink',
    name: 'rtrt',
    msg: 'rrrrrrrrrrrrrrrrrrrrrrrr',
    time: "10:35",
    unread: 3,
    pinned: false,
    online: true,
  },
  {
    id: 3,
    img: 'imageLink',
    name: 'rwetre',
    msg: 'songName',
    time: "04:00",
    unread: 0,
    pinned: false,
    online: true,
  },
  {
    id: 4,
    img: 'imageLink',
    name: 'retyyer',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 5,
    img: 'imageLink',
    name: 'eryuy',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 6,
    img: 'imageLink',
    name: 'erererwtre',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 7,
    img: 'imageLink',
    name: 'thghdrrtg',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 7,
    img: 'imageLink',
    name: 'thghdrrtg',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 7,
    img: 'imageLink',
    name: 'thghdrrtg',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
  {
    id: 7,
    img: 'imageLink',
    name: 'thghdrrtg',
    msg: 'songName',
    time: "08:42",
    unread: 0,
    pinned: false,
    online: false,
  },
];

const Chat_History = [
  {
    type: "msg",
    message: "Hi 👋🏻, How are ya ?",
    incoming: true,
    outgoing: false,
  },
  {
    type: "divider",
    text: "Today",
  },
  {
    type: "msg",
    message: "Hi 👋 Panda, not bad, u ?",
    incoming: false,
    outgoing: true,
  },
  {
    type: "msg",
    message: "Can you send me an abstarct image?",
    incoming: false,
    outgoing: true,
  },
  {
    type: "msg",
    message: "Ya sure, sending you a pic",
    incoming: true,
    outgoing: false,
  },

  {
    type: "msg",
    subtype: "img",
    message: "Here You Go",
    img: 'abstract',
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "img",
    message: "Here You Go",
    img: 'abstract',
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "img",
    message: "Here You Go",
    img: 'abstract',
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "img",
    message: "Here You Go",
    img: 'abstract',
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    message: "Can you please send this in file format?",
    incoming: false,
    outgoing: true,
  },

  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "reply",
    reply: "This is a reply",
    message: "Yep, I can also do that",
    incoming: false,
    outgoing: true,
  },
  {
    type: "msg",
    subtype: "reply",
    reply: "This is a reply",
    message: "Yep, I can also do that",
    incoming: false,
    outgoing: true,
  },
  {
    type: "msg",
    subtype: "reply",
    reply: "This is a reply",
    message: "Yep, I can also do that",
    incoming: false,
    outgoing: true,
  },
  {
    type: "msg",
    subtype: "reply",
    reply: "This is a reply",
    message: "Yep, I can also do that",
    incoming: false,
    outgoing: true,
  },
];

const Message_options = [
  {
    title: "Reply",
  },
  {
    title: "React to message",
  },
  {
    title: "Forward message",
  },
  {
    title: "Star message",
  },
  {
    title: "Report",
  },
  {
    title: "Delete Message",
  },
];

const Shared_docs = [
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "doc",
    message: "Yes sure, here you go.",
    incoming: true,
    outgoing: false,
  },
];

const Shared_links = [
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
  {
    type: "msg",
    subtype: "link",
    preview: 'preview',
    message: "Yep, I can also do that",
    incoming: true,
    outgoing: false,
  },
];

export {
  ChatList,
  Chat_History,
  Message_options,
  Shared_links,
  Shared_docs,
  CallList,
};